name: Auto Commit Gitartwork
on:
  push:
    schedule:
      - cron: '* */4 * * *'

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install gitartwork
        run: npm install -g gitartwork-cli

      - name: Generate gitartwork SVG
        run: gitartwork --user pal-sandeep --text "SANDEEP PAL"

      - name: Commit and push changes
        run: |
          git config --global user.name "Sandeep Pal"
          git config --global user.email "skumar8work@gmail.com"
          git add .
          git commit -m "ğŸ˜Šâ¤ğŸ‰"
          git push
